<?php

// $Id: block_tab.module,v 1.8 2011/02/09 05:53:16 hosszukalman Exp $

/**
 * Implementation of hook_menu().
 */
function block_tab_menu() {
  return array(
    'admin/settings/block_tab' => array(
      'type' => MENU_NORMAL_ITEM,
      'title' => 'Block tab settings',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('block_tab_admin_settings'),
      'access arguments' => array('administer block tab settings'),
      'file' => 'block_tab.admin.inc',
    ),
  );
}

/**
 * Implementation of hook_perm().
 */
function block_tab_perm() {
  return array('administer block tab settings');
}

/**
 * Implementation of hook_init().
 */
function block_tab_init() {
  $path = drupal_get_path('module', 'block_tab');
  drupal_add_css($path . '/css/block_tab.css');
  drupal_add_js($path . '/js/block_tab.js');
}

/**
 * Renders a region as a tabbed block group.
 */
function block_tab_blocks($region) {
  $region_setting = variable_get('block_tab-regions', array());

  if (!isset($region_setting[$region]) || (string) $region_setting[$region] != $region) {
    return theme_blocks($region);
  }

  $titles = array();
  $output = '';
  $first_flag = TRUE;

  if ($list = block_list($region)) {
    foreach ($list as $key => $block) {
      // $key == <i>module</i>_<i>delta</i>

      $titles[] = array(
        'title' => empty($block->subject) ? $key : $block->subject,
        'key' => $key,
        'active' => $first_flag ? ' active' : '',
      );
      $block->subject = '';

      $output .= '<div class="block_tab-block' . ($first_flag ? ' visible' : '') . '" id="block_tab-block-' . $key . '">' . theme('block', $block) . '</div>';
      $first_flag = FALSE;
    }
  }

  // Add any content assigned to this region through drupal_set_content() calls.
  $output .= drupal_get_content($region);

  $title_html = '';
  foreach ((array) $titles as $title) {
    $title_html .= '<span class="block_tab-title' . $title['active'] . '" id="block_tab-title-' . $title['key'] . '">' . check_plain($title['title']) . '</span>';
  }

  return '<div class="block_tab-titles" region="' . $region . '">' . $title_html . '</div>
          <div class="block_tab-blocks" region="' . $region . '">' . $output . '</div>';
}

/**
 * Implementation of hook_theme().
 */
function block_tab_theme() {
  return array(
    'blocks' => array(
      'arguments' => array('region' => array()),
      'function' => 'block_tab_blocks',
    )
  );
}