<?php
function da_press_releases_block($op = 'list', $delta = 0, $edit = array()) {
	switch($op) {
			case 'list':
			$blocks = array();

			$blocks[0] = array(
				'info' => t('Press Releases'),
        		'cache' => BLOCK_CACHE_GLOBAL,
			);

			$blocks[1] = array(
				'info' => t('Consumer Resource Articles'),
				'cache' => BLOCK_CACHE_GLOBAL,
			);

			return $blocks;
			
		case 'configure':
			$form['number_of_items'] = array(
				'#type' => 'select',
				'#title' => 'Number of items',
				'#default_value' => variable_get('da_press_releases_noi_'.$delta, 2),
				'#options' => range(1, 20)
			);

			return $form;
		case 'save':
			variable_set('da_press_releases_noi_'.$delta, $edit['number_of_items']);

		case 'view':
			drupal_add_css(drupal_get_path('module', 'da_press_releases').'/css/da_press_releases.css', 'module');
			
			if($delta) {
				$sql = "SELECT nid FROM {node} WHERE type = 'research_center_article' ORDER BY vid DESC LIMIT 0,%d";
				$result = db_query($sql, variable_get('da_press_releases_noi_'.$delta, 2)+1);
				
				$subject = "Consumer Resource Articles";
				$content = '<div class="da-research-center-block">';
				
				while($node = db_fetch_object($result)) {
					$node = node_load($node->nid);
					foreach($node->taxonomy as $term) {
						$content .= '<p class="pr-title">'.l($term->name, 'taxonomy/term/'.$term->tid).'</p>';
					}
					$content .= '<p class="pr-date">'.$node->title.'</p>';
					$content .= '<p class="pr-teaser">'.filter_xss($node->teaser, array('strong')).'</p>';
					$content .= '<p class="pr-rmore">'.l('Read More...', 'node/'.$node->nid).'</p>';
				}

				$content .= '</div>';
			} else {				
				$sql = "SELECT n.nid FROM {node} n INNER JOIN {content_type_press_release} f ON n.vid = f.vid WHERE n.type = 'press_release' ORDER BY  f.field_release_date_value DESC LIMIT 0,%d";
				$result = db_query($sql, variable_get('da_press_releases_noi_'.$delta, 2)+1);
			
				$content = '<div class="da-press-release-block">';
				$subject = 'Press Releases';
			
				while($node = db_fetch_object($result)) {
					$node = node_load($node->nid);
					$date = date_make_date((int)$node->field_release_date[0]["value"], date_default_timezone(), $node->field_release_date[0]["date_type"]);
					$content .= '<p class="pr-title">'.l($node->title, 'node/'.$node->nid).'</p>';
					$content .= '<p class="pr-date">'.date_format($date, 'n/j/Y').'</p>';
					$content .= '<p class="pr-teaser">'.filter_xss($node->teaser, array('strong')).'</p>';
					$content .= '<p class="pr-rmore">'.l('Read More...', 'node/'.$node->nid).'</p>';
				}
				$content .= '<p class="pr-rmore">'.l('View All', 'press_releases').'</p>';
				$content .= '</div>';
			}
			
			return array(
				'subject' => $subject,
				'content' => $content
			);
	}
}

function da_press_releases_menu() {
	$urls = array();
	$urls['press_releases'] = array(
    	'title' => 'Press Releases', 
    	'description' => 'Press Releases.', 
    	'page callback' => 'da_press_releases_view', 
    	'access arguments' => array('access content'), 
    	'type' => MENU_CALLBACK,
  	);
	return $urls;
}

function da_press_releases_view() {
	$content = '';
	$sql = "SELECT n.nid FROM {node} n INNER JOIN {content_type_press_release} f ON n.vid = f.vid WHERE n.type = 'press_release' ORDER BY  f.field_release_date_value DESC";
	$nodes = pager_query($sql, 10);
	while($node = db_fetch_object($nodes)) {
		$node = node_load($node->nid);
		$content .= node_view($node, TRUE);
	}
	$content .= theme('pager');
	return $content;
}