<?php

/**
 * @file
 *
 * Add select box on contact form
 *
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */

/**
 *
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */
function contact_listfield_info() {
  return array(
    'select' => array(
      'type' => 'list',
      'title' => t("List"),
      'description' => t("Add select box on contact form"),
    ),
  );
}

/**
 *
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */
function contact_field_add_field_listfield_form($form_state, $ss_field_name = NULL, $om_field_details = NULL) {
  drupal_set_title(t("Configure list field"));
  $form = array();
  $ss_option = ""; //initialize it first
  if (arg(3) != 'add') {
    $om_field_details = (object) _get_field_values($om_field_details);
    if (!empty($om_field_details->options)) {
      foreach ($om_field_details->options as $key => $value) {
        $ss_option .= $key ."|". $value;
      }
    }
    $form['#submit'] = array('contact_field_listfield_update');
  }
  else {
    $form['#submit'] = array('contact_field_listfield_submit');
    $form['#validate'] = array('contact_field_validate');
  }

  $form['name'] = array(
    '#type' => 'item',
    '#title' => t("Field name"),
    '#description' => t("Machine readable name of the field. This should only
      contain alphanumeric characters and underscore."),
    '#value' => $om_field_details->name,
    '#weight' => -50,
  );

  $form['contact_field_name'] = array(
    '#type' => 'hidden',
    '#value' => $om_field_details->name,
  );

  $form['field_type'] = array(
    '#type' => 'hidden',
    '#default_value' => 'select',
  );


  $form['contact_field_label'] = array(
    '#type' => 'textfield',
    '#title' => t("Field title"),
    '#description' => t("Provide the title of the field"),
    '#default_value' => $om_field_details->title,
    '#required' => TRUE,
    '#weight' => -49,
  );

  $form['contact_field_num_value'] = array(
    '#type' => 'select',
    '#title' => t("Number of value"),
    '#description' => t("Number of values allowed to enter. If 'Single'
      is selected, only one value can be selected."),
    '#options' => array(
      0 => t("Single"),
      1 => t("Multiple"),
    ),
    '#default_value' => isset($om_field_details->num_value) ? $om_field_details->num_value : 0,
    '#required' => TRUE,
    '#weight' => -48,
  );

  $form['contact_field_prefix'] = array(
    '#type' => 'textfield',
    '#title' => t("Prefix"),
    '#description' => t("Add prefix to add style to the field."),
    '#default_value' => isset($om_field_details->prefix) ? $om_field_details->prefix : "",
    '#weight' => -47,
  );

  $form['contact_field_suffix'] = array(
    '#type' => 'textfield',
    '#title' => t("Suffix"),
    '#description' => t("Add suffix to add style to the field."),
    '#default_value' => isset($om_field_details->suffix) ? $om_field_details->suffix : "",
    '#weight' => -46,
  );

  $form['contact_field_require'] = array(
    '#type' => 'radios',
    '#title' => t("Required?"),
    '#description' => t("Whether this field is mandatory."),
    '#options' => array(
      0 => t("No"),
      1 => t("Yes"),
    ),
    '#default_value' => isset($om_field_details->required) ? $om_field_details->required : 1,
    '#required' => TRUE,
    '#weight' => -45,
  );

  $form['contact_field_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t("Display this field"),
    '#description' => t("Check this box to make this field available on
      contact form."),
    '#default_value' => isset($om_field_details->enabled) ? $om_field_details->enabled : 1,
    '#weight' => -44,
  );

  $form['contact_field_weight'] = array(
    '#type' => 'textfield',
    '#title' => t("Weight"),
    '#size' => 10,
    '#description' => t("Fields with positive weight will sink.
      Negative weight will make the field pop up."),
    '#default_value' => isset($om_field_details->weight) ? $om_field_details->weight : 0,
    '#weight' => -43,
  );

  $form['contact_field_values'] = array(
    '#type' => 'textarea',
    '#title' => t("Allowed values"),
    '#description' => t("Add key-value pair in key|value format. Add each pair in separate line."),
    '#default_value' => (!empty($ss_option) ? $ss_option : ""),
    '#required' => TRUE,
    '#weight' => -42,
  );

  $form['contact_field_help'] = array(
    '#type' => 'textarea',
    '#title' => t("Help text"),
    '#description' => t("Help text will appear just beneath the field like this,
      to help user in filling value in the field."),
    '#default_value' => isset($om_field_details->description) ? $om_field_details->description : "",
    '#weight' => -41,
  );

  $form['contact_field_submit'] = array(
    '#type' => 'submit',
    '#value' => t("Save configuration"),
  );


  return $form;
}

/**
 *
 * @param $form
 * @param $form_values
 * @author Bhavin H. Joshi <bhavinjosi@joshics.in>
 */
function contact_field_listfield_submit($form, $form_values) {
  $ss_num_values = $form_values['values']['contact_field_num_value'];
  $ss_field_settings['multiple'] = ($ss_num_values) ? TRUE : FALSE;
  $ss_field_name = $form_values['values']['contact_field_name'];
  $ss_field_type = $form_values['values']['field_type'];
  $ss_field_required = $form_values['values']['contact_field_require'];
  $ss_field_enabled = $form_values['values']['contact_field_enabled'];
  $ss_field_settings['title'] = $form_values['values']['contact_field_label'];
  $ss_field_settings['prefix'] = $form_values['values']['contact_field_prefix'];
  $ss_field_settings['suffix'] = $form_values['values']['contact_field_suffix'];
  $ss_field_settings['num_value'] = $ss_num_values;
  $ss_field_weight = $form_values['values']['contact_field_weight'];
  $ss_field_settings['description'] = $form_values['values']['contact_field_help'];
  $am_options = explode("\n", $form_values['values']['contact_field_values']);
  foreach ($am_options as $option) {
    $option = contact_field_filter_xss($option);
    if (strpos($option, '|') !== FALSE) {
      list($key, $value) = explode("|", $option);
      $ss_field_settings['options'][$key] = $value;
    }
  }

  db_query("INSERT INTO {contact_fields} VALUES('%s', '%s', '%s', %d, %d, %d, %d, '%s')",
    $ss_field_name, $ss_field_type, serialize($ss_field_settings),
    $ss_field_required, $ss_field_enabled, $ss_field_weight, 0, NULL);
  drupal_set_message($ss_field_settings['title'] ." ". t("created"));
  drupal_goto('admin/build/contact/manage');
}

/**
 *
 * @param unknown_type $form
 * @param unknown_type $form_values
 */
function contact_field_listfield_update($form, $form_values) {
  $ss_num_values = $form_values['values']['contact_field_num_value'];
  $ss_field_settings['multiple'] = ($ss_num_values) ? TRUE : FALSE;
  $ss_field_name = $form_values['values']['contact_field_name'];
  $ss_field_type = $form_values['values']['field_type'];
  $ss_field_required = $form_values['values']['contact_field_require'];
  $ss_field_enabled = $form_values['values']['contact_field_enabled'];
  $ss_field_settings['title'] = $form_values['values']['contact_field_label'];
  $ss_field_settings['prefix'] = $form_values['values']['contact_field_prefix'];
  $ss_field_settings['suffix'] = $form_values['values']['contact_field_suffix'];
  $ss_field_settings['num_value'] = $ss_num_values;
  $ss_field_weight = $form_values['values']['contact_field_weight'];
  $ss_field_settings['description'] = $form_values['values']['contact_field_help'];
  $am_options = explode("\n", $form_values['values']['contact_field_values']);
  foreach ($am_options as $option) {
    $option = contact_field_filter_xss($option);
    if (strpos($option, '|') !== FALSE) {
      list($key, $value) = explode("|", $option);
      $ss_field_settings['options'][$key] = $value;
    }
  }

  db_query("UPDATE {contact_fields} SET settings = '%s', enabled = %d,
    required = %d, weight = %d WHERE field_name = '%s'", serialize($ss_field_settings),
    $ss_field_enabled, $ss_field_required, $ss_field_weight, $ss_field_name);

  drupal_set_message($ss_field_settings['title'] ." ". t("Updated"));
  drupal_goto('admin/build/contact/manage');
}
